/* ==================   INCLUDES   ================  */

#include <linux/limits.h>
#include <stdio.h>
#include <raylib.h>
#include <math.h>

/* =================== DEFINES   ====================  */

#define WIDTH 1200
#define HEIGHT 900 //Yup I love 4:3 

#define FPS 120


#define TRIANGLE_SIDE_LENGTH 530.0f
#define DEPTH_STEP 1
#define MAX_DEPTH 16

#define NEAT_VIOLET (Color){19,9,69,255}
#define BLOOD (Color){245,31,60,255}

/* ========================== YAPPING  ===================== */

            /*
                    What we do today? More math fuckery!!! (Well pong too...but I need change so I started to work on this too)
                    What is Sierpinski triangle?
                        1-It's a recursive pattern that formed by an uni-triangle? is that a thing? yk...the one with PI/3 angles each and all side lengths are equal...that one
                        
                        and if you're not comfortable with working on radians I got you... found this in raylib.h

                        #ifndef DEG2RAD
                        #define DEG2RAD (PI/180.0f) all you gotta do is degree*DEG2RAD
                         

                        Important shit to know to create this:
                            1- Start with a uni-triangle(Yeah...I'll call it that you got the idea)
                            2-Divide it to 4 uni-triangles within the first one and remove the one in the middle

                            That's it!

                            Do I know how to create it? Abso-fucking-litely not but hey...that's the charm B)

                    Thile file requires external lib: Raylib you can install it by pacman -S raylib if you are on Arch and I am pretty sure that other distros have that too
                    just try dnf,apt-get,apt,pkg if you're on Termux idk you'll get her eventually
                    and to compile: cc (or gcc) src.c -o output -lraylib (and -lm if I include math too)

                    If you've seen my other graphic projects you know how I sector things with comment blocks and use camelCase for my own fucntions to reduce confusion with
                    raylib functions (Which are all in PascalCase (as far as I've seen))


                    Never drawn a triangle in raylib before so we're head-diving into raylib header to extract some shit 

                    DrawTriangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color);                                // Draw a color-filled triangle (vertex in counter-clockwise order!)

                    RLAPI void DrawTriangleLines(Vector2 v1, Vector2 v2, Vector2 v3, Color color);        // Draw triangle outline (vertex in counter-clockwise order!)
                    RLAPI void DrawTriangleFan(const Vector2 *points, int pointCount, Color color);       // Draw a triangle fan defined by points (first vertex is the center)
                    RLAPI void DrawTriangleStrip(const Vector2 *points, int pointCount, Color color);     // Draw a triangle strip defined by points

                    those three was what I've found but all of them using Vectors for points...for me this is some computational waste I need to calculate the perfect 
                    eqaul distances from a center... First Idea...with a given radius draw a circle and draw a triangle within the circle where all 3 vertices of the triangle 
                    are on the arc of the said circle...


                    Now...should I recurse or loop over the base triangle...
                    main question is... if I divide it to 4 does it split the main triangle in the middle 
                    
                    let's say I have a triangle with a side length of 200 the mid point height would be 100*sqrt(3) now let's split it to for 50 each 25*sqrt(3)*4 is 100*sqrt(3) indeed so either I suck at math(%99.9 truth)
                    or splitting a uni-triangle to 4 doesn't fuck my intention

                    And I know I say that a lot but I'd failed math in highschool lmfao...


                    Here is the copypasta from Wikipedia page for me (so you) to think

                        Shrinking and duplication
                    The same sequence of shapes, converging to the Sierpiński triangle, can alternatively be generated by the following steps:

                    Start with any triangle in a plane (any closed, bounded region in the plane will actually work). The canonical Sierpiński triangle uses an equilateral triangle with a base 
                    parallel to the horizontal axis (Done!).
                    
                    1-Shrink the triangle to ⁠1/2 height and ⁠ 1/2 width, make three copies, and position the three shrunken triangles so that each triangle touches the two other triangles at a corner

                    lowkey...I want to scream...(yeah that's me not wikipedia)

                    Note the emergence of the central hole—because the three shrunken triangles can between them cover only ⁠
                    3/4 of the area of the original. (Holes are an important feature of Sierpiński's triangle.)
                    Repeat step 2 with each of the smaller triangles .


                    And yeah... I am working with a notebook (the OG tool) for math lmfao I can't be bothered to use a calculator


                    FLAG_MSAA_4X_HINT       = 0x00000020 found that for anti-aliasing yk...we're diving into fractions so it's neat to have for you guys...my RX580 won't be able to do much shit anways

            */

/* ========== OBJECTS  =====================  */




/* ============== FUNCTION PROTOTYPES  ================  */

void drawItPlease(Vector2 peak,float length);
void recursiveDrawing(Vector2 peak,float length,int maxDepth,int currentDepth);

/* ============== GLOBAL VARS ===================  */

//Lol nothing to see here move on civilian




int main(void)
{

    InitWindow(WIDTH, HEIGHT,"Thingyangle");
    if (!IsWindowReady()) { perror("Windows suck as always\n"); return(-1); }
    SetTargetFPS(FPS);
    SetConfigFlags(FLAG_MSAA_4X_HINT);

    int iterDepth = 0;
    int depth = 0;
    double lastPrint = 0.0l;
    while (!WindowShouldClose()) {
        if (IsKeyPressed(KEY_ESCAPE)) { CloseWindow(); }
        if (IsKeyPressed(KEY_SPACE)) { 
            if (iterDepth > MAX_DEPTH) { iterDepth = MAX_DEPTH; /*Do aboso-fucking-lutiely nothing*/}
            else {
                iterDepth++;  lastPrint = GetTime();
            }
        }

        if (GetTime() - lastPrint >= 10.0l) {
            iterDepth++;
            lastPrint = GetTime();
        }
        

        BeginDrawing();

        ClearBackground(NEAT_VIOLET);
        DrawText("Press ESC to escape", 13,13, 26,BLOOD);
        DrawText(TextFormat("Current Depth Level: %d",iterDepth),13, 53,26,BLOOD);
        Vector2 vertex = {WIDTH/2.0f,HEIGHT/5.0f};
        recursiveDrawing(vertex,TRIANGLE_SIDE_LENGTH,iterDepth, depth);
        
        EndDrawing();
    }



    CloseWindow();

    return(0);
}

/*  ==================  FUNCTION BODIES  ==================  */


//IFUCKINGHATEMATH
void drawItPlease(Vector2 peak,float length)
{
    float y = peak.y + length * sinf(PI/3);
    Vector2 left = (Vector2){peak.x - length/2,y};
    Vector2 right = (Vector2){peak.x + length/2,y}; 

    DrawTriangle(peak,left,right,BLOOD);
}

//What should I recurse... tho I hate recursion this shit is 3^n so give it more than 10 and you'll be the first the watch your rig's funeral
void recursiveDrawing(Vector2 peak,float length,int maxDepth,int currentDepth)
{
    //So you don't blow your PC but the definition of Sierpinski Triangle is infinite recursions but...we have finite ram lol
    if (currentDepth >= maxDepth) { 
        drawItPlease(peak, length);
        return;
    }

    
    currentDepth++; //Don't increment the memory address lmfao that's gonna get incramented thrice as much isn't it?

    float y = peak.y + length/2 * sinf(PI/3);
    Vector2 left = (Vector2){peak.x - length/4, y};
    Vector2 right = (Vector2){peak.x + length/4, y}; 

    recursiveDrawing(peak,length/2, maxDepth,currentDepth);
    recursiveDrawing(left,length/2, maxDepth,currentDepth);
    recursiveDrawing(right,length/2, maxDepth,currentDepth);

    //I should probably split the logic and drawing to two different funcitons but...

}